### Create check-in request
POST http://localhost:8080/api/stay-requests/check-in
Content-Type: application/json

{
  "patientId": 1,
  "admissionDate": "2026-02-10",
  "dischargeDate": "2026-02-20"
}

### Create expansion request
POST http://localhost:8080/api/stay-requests/expansion
Content-Type: application/json

{
  "patientId": 1,
  "admissionDate": "2026-02-21",
  "dischargeDate": "2026-03-01"
}

###
POST http://localhost:8080/api/rooms
Content-Type: application/json

{
"roomNumber": 1,
"isOccupied": false
}
### Approve stay request
POST http://localhost:8080/api/stay-requests/1/approve?roomId=1

### Reject stay request
POST http://localhost:8080/api/stay-requests/1/reject

### Add diary entry
POST http://localhost:8080/api/diary-entries/medical-card/1
Content-Type: text/plain

Сегодня хорошее самочувствие
